### PR TITLE
Update to latest basic-cli release

### PR DESCRIPTION
**Pull request by lukewilliamboswell**
This PR;
- Updates to latest basic-cli release
- Updates example to latest basic-web server
- Upgrades argument parsing using Weaver
- Adds support for providing a path to templates
- Adds support for alternate template extensions
- Adds INFO messages for each step of processing

## Previews
Screenshot 2024-07-10 at 20 13 07
Screenshot 2024-07-10 at 20 16 10

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
@isaacvando -- just waiting to see if 0.12.0 comes out of pre-release, but thought I would share some updates.

**Comment by isaacvando** [comment]
@lukewilliamboswell Thanks for making all these great updates! 

I'm hesitant to add a command line option for specifying alternate extensions to the CLI because I'm not sure if the benefit of it is great enough to justify adding a configuration option. I prefer to have less options and be explicit about the fact that the template is an RTL template and not something else. The biggest reason I can see for allowing it is so that the template files can still have the file type's default syntax highlighting, but this can be resolved instead (in VSCode at least) by creating a file association like this in settings.json:
```json
"files.associations": {
  "*.rtl": "html"
}
```
(This reminds me that I should probably add a note about this to the readme).

Thoughts? What do you see as the main value of adding the ability to configure it?

There are some other small tweaks I'd like to make to the PR before merging it, but I may not have time to until this weekend/next week. Thanks again for the updates!

**Comment by lukewilliamboswell** [comment]
Yeah syntax highlighting was the main motivation, I'll have to look into that. The other is that I was testing out using the tailwindcss CLI and it looks for templates. I'll see if I can get it to pickup a .rtl file. 

No stress if you don't think it's right or want to make changes.

I've got a project I'm starting on and thought I'd give rtl a go. I suspect there's a bunch of things I'll want to try out. 

I'll make a PR if I think it's helpful more generally.

**Comment by isaacvando** [comment]
Cool! Let me know how the project goes and if you run into any issues.

It looks like you can add `rtl` as an extension for tailwind to search for and it should work because it's just using regexes to look for class names in files https://tailwindcss.com/docs/content-configuration#class-detection-in-depth. If that doesn't actually work, then I think it would be a good idea to add the extension flag!

**Comment by lukewilliamboswell** [comment]
@isaacvando 

I've noticed this issue, if you run from another directory the check fails.

```
$ rtl -i ./tailwind/templates -o ./tailwind/templates
INFO: Searching for templates in ./tailwind/templates ...
INFO: Reading templates...
INFO: Compiling templates...
INFO: Generated ./tailwind/templates/Pages.roc in 5ms
INFO: Checking generates ./tailwind/templates/Pages.roc for syntax errors...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Outstanding references to the derived module
Location: crates/compiler/load_internal/src/file.rs:3277:29
```
```
$ cd tailwind/templates
$ roc check Pages.roc
0 errors and 0 warnings found in 13 ms
```

**Comment by isaacvando** [comment]
@lukewilliamboswell I wasn't able to reproduce that compiler crash; is there more info you can share about what you did to get it?

**Comment by lukewilliamboswell** [comment]
> @lukewilliamboswell I wasn't able to reproduce that compiler crash; is there more info you can share about what you did to get it?

Sure, it's when you are in a parent directory and the templates are in a descendent somewhere. That seems to be all that is required. 

It's a roc issue and not specific to RTL per se.

**Comment by isaacvando** [comment]
> Sure, it's when you are in a parent directory and the templates are in a descendent somewhere. That seems to be all that is required.

Hm, I'm still not able to get that to happen on my machine. I will leave it for the time being since it is an issue with roc check itself and doesn't block generating Pages.roc.

Can you explain what the benefit of this [commit](https://github.com/isaacvando/rtl/pull/1/commits/728c98bd75331e98b00fe701be616e1a9cd83ec4) is?

**Comment by lukewilliamboswell** [comment]
Sure, that commit prevents you from accidentally putting a Str in where a template is expected, or a template where a Str is expected.

**Comment by isaacvando** [comment]
@lukewilliamboswell I am going to go ahead and merge this so I can start making other changes based on the main branch rather than branching off of this branch or continuing to update this PR. I added a note to the readme and will update the url if the prerelease url changes.

**Pull request merged**
